routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Exports\DeviceTypesExport;
use App\Exports\DoctorsExport;
use App\Exports\EmployeesExport;
use App\Exports\PracticesExport;
use App\Exports\RegionalAdminsExport;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\QualificationsExport;
use App\Exports\ServicesExport;
use App\Exports\DevicesExport;
use App\Exports\PracticeDevicesExport;
use App\Exports\ManufacturersExport;

Route::get('/', 'HomeController@index')->name('home');

Route::group([
    'prefix' => '{locale}',
    'where' => ['locale' => '[a-zA-Z]{2}'],
    'middleware' => 'setlocale',
], function () {
    Auth::routes();
});

Route::group([
    'prefix' => '{locale}',
    'where' => ['locale' => '[a-zA-Z]{2}'],
    'middleware' => 'setlocale',
], function () {

    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => 'role:superadmin'], function () {
            Route::get('/', 'HomeController@index')->name('admin.home');
            Route::resource('/users', 'UsersController');
            Route::post('/elearning/filter', 'ElearningController@filterDevices')->name('admin.filter');
            Route::get('/doctors', 'UsersController@doctors')->name('doctors.home');
            Route::get('/doctors/createdoctor', 'UsersController@addDoctor');
            Route::get('/doctors/{id}/editDoctor', 'UsersController@editDoctor');
            Route::post('/doctors/storedoctor', 'UsersController@storeDoctor');
            Route::get('/reports/generate', 'ReportController@generate')->name('report.generate');
            Route::post('/reports/generate', 'ReportController@dataCreate');

            Route::post('/reports/store', 'ReportController@store')->name('report.store');

            //Route::post('/reports/store', 'ReportController@dataStore')->name('report.store');
            Route::get('/reports', 'ReportController@index');
            Route::get('/show/reports', 'ReportController@show')->name('report.show');
            Route::post('/report/{id}/pdf-download', 'ReportController@downloadPDF')->name('report.download');
            Route::delete('/report/{id}/delete', 'ReportController@delete')->name('report.delete');
            Route::get('/report/{id}/edit', 'ReportController@dataCreate')->name('report.edit');


            Route::resource('/sites', 'SiteController');
            Route::post('/elearning/getsites', 'SiteController@getSitesByPractice')->name('admin.getSitesByPractice');


            Route::group(['prefix' => 'download'], function () {
                Route::get('/devices', function () {
                    return Excel::download(new DevicesExport, 'Devices.xlsx');
                })->middleware('auth');
                Route::get('/practicedevices', function () {
                    return Excel::download(new PracticeDevicesExport, 'PracticeDevices.xlsx');
                })->middleware('auth');
                Route::get('/services', function () {
                    return Excel::download(new ServicesExport, 'Services.xlsx');
                })->middleware('auth');
                Route::get('/qualifications', function () {
                    return Excel::download(new QualificationsExport, 'Qualifications.xlsx');
                })->middleware('auth');
                Route::get('/manufacturers', function () {
                    return Excel::download(new ManufacturersExport, 'Manufacturer.xlsx');
                })->middleware('auth');
                Route::get('/types', function () {
                    return Excel::download(new DeviceTypesExport, 'DeviceTypes.xlsx');
                })->middleware('auth');
                Route::get('/practice', function () {
                    return Excel::download(new PracticesExport, 'Practice.xlsx');
                })->middleware('auth');
                Route::get('/employee', function () {
                    return Excel::download(new EmployeesExport, 'Employees.xlsx');
                })->middleware('auth');
                Route::get('/doctor', function () {
                    return Excel::download(new DoctorsExport, 'Doctors.xlsx');
                })->middleware('auth');
                Route::get('/admin', function () {
                    return Excel::download(new RegionalAdminsExport, 'RegionalAdmins.xlsx');
                })->middleware('auth');
            });


            Route::get('/changelogin/', 'UsersController@changelogin');
            Route::put('/changelogin/store', 'UsersController@updatepassword');


            Route::get('/doctors/createpassword/{token}', 'SendMailController@createpassword');
            Route::put('/doctors/createpassword/{token}/store', 'SendMailController@updatepassword');
            Route::get('/doctor/{id}/edit', 'UsersController@editDoctor');
            Route::get('/employees', 'UsersController@employees')->name('employees.index');
            Route::get('/admins', 'UsersController@admins')->name('admins.index');
            Route::get('/createemployee', 'UsersController@addEmployee');
            Route::get('/createadmin', 'UsersController@addAdmin');
            Route::post('/employees/storeemployee', 'UsersController@storeEmployee');
            Route::post('/admins/storeadmin', 'UsersController@storeAdmin');
            Route::put('/employees/{id}', 'UsersController@updateEmployee');
            Route::put('/admin/{id}', 'UsersController@updateAdmin');
            Route::get('/employee/{id}/edit', 'UsersController@editEmployee');
            Route::get('/admin/{id}/edit', 'UsersController@editAdmin');
            Route::resource('/settings', 'SettingsController');
            Route::resource('/devices', 'DevicesController');
            Route::resource('/qualifications', 'QualificationsController');
            Route::resource('/types', 'TypesController');
            Route::resource('/practices', 'PracticesController');
            Route::resource('/translations', 'TranslationsController');
            Route::resource('/manufacturers', 'ManufacturersController');
            Route::resource('/services', 'ServicesController');
            Route::resource('/practice-devices', 'PracticeDevicesController');
            Route::resource('/elearning', 'ElearningController');
            Route::resource('/training', 'TrainingController');
            Route::resource('/elearning/{id}/questions', 'ElearningQuestionController');
            Route::get('/elearning/download/{name}', 'ElearningController@download_pdf')->name('download_pdf');
            Route::get('/elearning/file/{name}', 'ElearningController@viewFile')->name('elearning.file.view');
            Route::get('/elearning/{id}/file', 'ElearningController@deleteFile')->name('elearning.file.delete');
            Route::get('/training/download/{name}', 'TrainingController@viewFile')->name('training.download');
            Route::get('/training/{id}/file', 'TrainingController@deleteFile')->name('training.file.delete');
        });
    });


    // Routes for Doctor role
    Route::group(['middleware' => 'role:doctor', 'prefix' => 'account', 'namespace' => 'Doctor'], function () {
        Route::name('doctor.')->group(function () {

            Route::get('/', 'HomeController@index')->name('home');
            Route::resource('/devices', 'PracticeDevicesController');
            Route::get('/report/{id}', 'PracticeDevicesController@report');
            Route::get('/createtest/{id}', 'PracticeDevicesController@createtest');
            Route::post('/createtest/store', 'PracticeDevicesController@storetest');
            Route::post('/devices/filter', 'PracticeDevicesController@filterDevices');
            Route::post('/get-devices-by-practice', 'PracticeDevicesController@getDevicesByPractice')->name('getDevicesByPractice');
            Route::post('/employee/add', 'UsersController@storeEmployee');
            Route::resource('/employees', 'UsersController');
            Route::get('/profile/edit', 'UsersController@profileEdit')->name('profile.edit');
            Route::resource('/training', 'DoctorTrainingController');
            Route::get('/training/download/{name}', 'DoctorTrainingController@downloadFile');
            Route::post('/profile/update', 'UsersController@profileUpdate')->name('profile.update');
            Route::post('/profile/password', 'UsersController@profileUpdatePassword')->name('profile.update.password');
            Route::resource('/elearning', 'DoctorElearningController');
            Route::resource('/elearning/{id}/questions', 'DoctorElearningQuestionController');
            Route::get('/elearning/download/{name}', 'DoctorElearningController@download_pdf')->name('download_pdf');
            Route::get('/elearning/file/{name}', 'ElearningController@viewFile')->name('elearning.file.view');
            Route::get('/elearning/{id}/file', 'ElearningController@deleteFile')->name('elearning.file.delete');
            Route::get('/training/file/{name}', 'DoctorTrainingController@viewFile')->name('training.file.view');
            Route::get('/training/{id}/file', 'DoctorTrainingController@deleteFile')->name('training.file.delete');

        });
    });


    Route::group(['middleware' => 'role:employee', 'prefix' => 'user', 'namespace' => 'User'], function () {
        Route::name('user.')->group(function () {

            Route::get('/', 'HomeController@index')->name('home');
            Route::get('/training', 'UserTrainingController@index');
            Route::get('/training/{name}', 'UserTrainingController@downloadFile');
            Route::resource('/devices', 'PracticeDevicesController');

app/Http/Controllers/User/HomeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Practice;
use App\Models\Translation;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Models\Device;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @param Request $request
     * @return Factory|View
     * @throws Exception
     */
    public function index(Request $request)
    {
        $practice = auth()->user()->practice;
        $devices = $practice->devices->where('pivot.deleted_at', null)->sortBy('pivot.next_validation_date');
        if ($request->ajax()) return datatables()->of($devices)->make(true);
        $translations = Translation::all()->pluck(app()->getLocale(), 'short_code');
        $meta_title = $translations['dashboard'] ?? 'Dashboard';
        $data = [
            'meta_title' => $meta_title,
            'devices' => [],
            'parent_link' => '/' . app()->getLocale() . '/account',
        ];
        return view('user.home', $data);
    }
}

app/Http/Controllers/User/QualificationsController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Translation;
use Illuminate\Http\Request;
use App\Models\Qualification;
use Illuminate\Support\Facades\Validator;

class QualificationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $translations = Translation::get()->pluck(app()->getLocale(), 'short_code');
        $data = [
            'meta_title' => $translations['qualif'] ?? 'Qualifications',
            'parent_link' => route('qualifications.index', app()->getLocale()),
            'date' => Qualification::getQualification(),
        ];
        return view('qualifications.home',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $translations = Translation::get()->pluck(app()->getLocale(), 'short_code');
        $data = [
            'meta_title' => $translations['qualif'] ?? 'Qualification',
            'meta_parent' => $translations['add_qualification'] ?? 'Add qualification',
            'parent_link' => route('qualifications.index', app()->getLocale()),
        ];
        return view('qualifications.create',$data);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $translations = Translation::get()->pluck(app()->getLocale(), 'short_code');
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
        ]);

        Qualification::storeQualification($request->all());

        $request->session()->flash('type', 'success');
        $request->session()->flash('message', $translations['qual_succ_created'] ?? 'Qualification successfully created');
        return redirect()->route('qualifications.index',[app()->getLocale()]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$lang,$id)
    {
        $translations = Translation::get()->pluck(app()->getLocale(), 'short_code');
        $date = Qualification::getQualificationById($id);
        if (!$date) {
            return redirect()->route('qualifications.index',[app()->getLocale()])->withErrors(['error' => $translations['qual_not_found'] ?? 'Qualification not found']);
        }

        $data = [
            'meta_title' => $translations['qualif'] ?? 'Qualifications',
            'meta_parent' => $translations['edit_qual'] ?? 'Edit qualification',
            'parent_link' => route('qualifications.index', app()->getLocale()),
            'date' => $date,
        ];
        return view('qualifications.edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$lang, $id)
    {
        $translations = Translation::get()->pluck(app()->getLocale(), 'short_code');
        $request->validate([
            'name' => ['required', 'string', 'max:255'],
        ]);
        $date = Qualification::getQualificationById($id);
        if (!$date) {
            return redirect()->route('qualifications.index',[app()->getLocale()])->withErrors(['error' => $translations['qual_not_found'] ?? 'Qualification not found']);
        }

        Qualification::updateQualification($date,$request->all());

        $request->session()->flash('type', 'success');
        $request->session()->flash('message', $translations['qual_succ_update'] ?? 'Qualification successfully updated');
        return redirect()->route('qualifications.index',[app()->getLocale()]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$lang, $id)
    {
        $translations = Translation::get()->pluck(app()->getLocale(), 'short_code');
        $qualification = Qualification::getQualificationById($id);
        if (!$qualification) {
            return redirect()->route('doctors.index',[app()->getLocale()])->withErrors(['error' => $translations['doc_not_found'] ?? 'Doctor not found']);
        }

        Qualification::deleteQualification($qualification);

        session()->flash('type', 'success');
        session()->flash('message', $translations['qual_del'] ?? 'Qualification Deleted');
        return redirect()->route('qualifications.index',[app()->getLocale()]);

    }

}

app/Http/Controllers/User/UserTrainingController.php
<?php

namespace App\Http\Controllers\User;

use App\Models\Training;
use App\Models\Translation;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Response;
use Illuminate\View\View;

class UserTrainingController extends Controller
{
    /**
     * @param Request $request
     * @return Factory|View
     * @throws Exception
     */
    public function index(Request $request)
    {
        if ($request->ajax()) return datatables()->of(Training::with('device')->get())->make(true);
        $translations = Translation::all()->pluck(app()->getLocale(), 'short_code');
        $meta_title = $translations['training_documents'] ?? 'Training documents';
        $data = [
            'meta_title' => $meta_title,
            'trainings' => [],
            'parent_link' => '/' . app()->getLocale().'/user/training',
        ];
        return view('user.training.home', $data);
    }



        public function downloadFile($lang,$name)
    {
        $file_path = storage_path() .'/app/public/trainings/'. $name;
        return Response::download($file_path, $name);
    }



}

resources/views/user/profile/edit.blade.php
@extends('layouts.user')
@section('meta_title', $meta_title)
@section('meta_title', $meta_title)@section('description')
    <div class="description">{{$translations['employee_profile_edit_desc'] ?? 'action'}}</div>
@endsection
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST"
                          action="{{ route('user.profile.update',['locale'=>app()->getLocale(),'id'=>$user->id] ) }}">
                        @csrf

                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">{{ $translations['name'] ?? 'name' }}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                       name="name" value="{{$user->name}}" required autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{ $translations['last_name'] ?? 'last_name' }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror"
                                       name="last_name" value="{{$user->last_name}}" required>

                                @error('last_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{ $translations['email'] ?? 'email' }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                       name="email" value="{{$user->email}}" required>

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{ $translations['title'] ?? 'title' }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror"
                                       name="title" value="{{$user->title}}" required>

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{ $translations['phone'] ?? 'phone' }}</label>

                            <div class="col-md-6">
                                <input id="email" type="text"
                                       class="form-control @error('email') is-invalid @enderror"
                                       name="phone" value="{{$user->phone}}" required>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ $translations['update'] ?? 'Update' }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8 mt-4" >
            <div class="card">
                <div class="card-body">
                    <form method="POST"
                          action="{{ route('doctor.profile.update.password',['locale'=>app()->getLocale()] ) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="old_password" class="col-md-4 col-form-label text-md-right">{{ $translations['old_password'] ?? 'old_password' }}</label>

                            <div class="col-md-6">
                                <input id="old_password" type="password"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="old_password" value="" required autocomplete="password" autofocus>

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">{{ $translations['new_password'] ?? 'new_password' }}</label>

                            <div class="col-md-6">
                                <input id="password" type="password"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="password" value="" required autofocus>

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password_confirmation" class="col-md-4 col-form-label text-md-right">{{ $translations['confirm_new_password'] ?? 'confirm_new_password' }}</label>

                            <div class="col-md-6">
                                <input id="password_confirmation" type="password"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="password_confirmation" value="" required autofocus>

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ $translations['update'] ?? 'Update' }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection