routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Exports\DeviceTypesExport;
use App\Exports\DoctorsExport;
use App\Exports\EmployeesExport;
use App\Exports\PracticesExport;
use App\Exports\RegionalAdminsExport;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\QualificationsExport;
use App\Exports\ServicesExport;
use App\Exports\DevicesExport;
use App\Exports\PracticeDevicesExport;
use App\Exports\ManufacturersExport;

Route::get('/', 'HomeController@index')->name('home');

Route::group([
    'prefix' => '{locale}',
    'where' => ['locale' => '[a-zA-Z]{2}'],
    'middleware' => 'setlocale',
], function () {
    Auth::routes();
});

Route::group([
    'prefix' => '{locale}',
    'where' => ['locale' => '[a-zA-Z]{2}'],
    'middleware' => 'setlocale',
], function () {

    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => 'role:superadmin'], function () {
            Route::get('/', 'HomeController@index')->name('admin.home');
            Route::resource('/users', 'UsersController');
            Route::post('/elearning/filter', 'ElearningController@filterDevices')->name('admin.filter');
            Route::get('/doctors', 'UsersController@doctors')->name('doctors.home');
            Route::get('/doctors/createdoctor', 'UsersController@addDoctor');
            Route::get('/doctors/{id}/editDoctor', 'UsersController@editDoctor');
            Route::post('/doctors/storedoctor', 'UsersController@storeDoctor');
            Route::get('/reports/generate', 'ReportController@generate')->name('report.generate');
            Route::post('/reports/generate', 'ReportController@dataCreate');

            Route::post('/reports/store', 'ReportController@store')->name('report.store');

            //Route::post('/reports/store', 'ReportController@dataStore')->name('report.store');
            Route::get('/reports', 'ReportController@index');
            Route::get('/show/reports', 'ReportController@show')->name('report.show');
            Route::post('/report/{id}/pdf-download', 'ReportController@downloadPDF')->name('report.download');
            Route::delete('/report/{id}/delete', 'ReportController@delete')->name('report.delete');
            Route::get('/report/{id}/edit', 'ReportController@dataCreate')->name('report.edit');


            Route::resource('/sites', 'SiteController');
            Route::post('/elearning/getsites', 'SiteController@getSitesByPractice')->name('admin.getSitesByPractice');


            Route::group(['prefix' => 'download'], function () {
                Route::get('/devices', function () {
                    return Excel::download(new DevicesExport, 'Devices.xlsx');
                })->middleware('auth');
                Route::get('/practicedevices', function () {
                    return Excel::download(new PracticeDevicesExport, 'PracticeDevices.xlsx');
                })->middleware('auth');
                Route::get('/services', function () {
                    return Excel::download(new ServicesExport, 'Services.xlsx');
                })->middleware('auth');
                Route::get('/qualifications', function () {
                    return Excel::download(new QualificationsExport, 'Qualifications.xlsx');
                })->middleware('auth');
                Route::get('/manufacturers', function () {
                    return Excel::download(new ManufacturersExport, 'Manufacturer.xlsx');
                })->middleware('auth');
                Route::get('/types', function () {
                    return Excel::download(new DeviceTypesExport, 'DeviceTypes.xlsx');
                })->middleware('auth');
                Route::get('/practice', function () {
                    return Excel::download(new PracticesExport, 'Practice.xlsx');
                })->middleware('auth');
                Route::get('/employee', function () {
                    return Excel::download(new EmployeesExport, 'Employees.xlsx');
                })->middleware('auth');
                Route::get('/doctor', function () {
                    return Excel::download(new DoctorsExport, 'Doctors.xlsx');
                })->middleware('auth');
                Route::get('/admin', function () {
                    return Excel::download(new RegionalAdminsExport, 'RegionalAdmins.xlsx');
                })->middleware('auth');
            });


            Route::get('/changelogin/', 'UsersController@changelogin');
            Route::put('/changelogin/store', 'UsersController@updatepassword');


            Route::get('/doctors/createpassword/{token}', 'SendMailController@createpassword');
            Route::put('/doctors/createpassword/{token}/store', 'SendMailController@updatepassword');
            Route::get('/doctor/{id}/edit', 'UsersController@editDoctor');
            Route::get('/employees', 'UsersController@employees')->name('employees.index');
            Route::get('/admins', 'UsersController@admins')->name('admins.index');
            Route::get('/createemployee', 'UsersController@addEmployee');
            Route::get('/createadmin', 'UsersController@addAdmin');
            Route::post('/employees/storeemployee', 'UsersController@storeEmployee');
            Route::post('/admins/storeadmin', 'UsersController@storeAdmin');
            Route::put('/employees/{id}', 'UsersController@updateEmployee');
            Route::put('/admin/{id}', 'UsersController@updateAdmin');
            Route::get('/employee/{id}/edit', 'UsersController@editEmployee');
            Route::get('/admin/{id}/edit', 'UsersController@editAdmin');
            Route::resource('/settings', 'SettingsController');
            Route::resource('/devices', 'DevicesController');
            Route::resource('/qualifications', 'QualificationsController');
            Route::resource('/types', 'TypesController');
            Route::resource('/practices', 'PracticesController');
            Route::resource('/translations', 'TranslationsController');
            Route::resource('/manufacturers', 'ManufacturersController');
            Route::resource('/services', 'ServicesController');
            Route::resource('/practice-devices', 'PracticeDevicesController');
            Route::resource('/elearning', 'ElearningController');
            Route::resource('/training', 'TrainingController');
            Route::resource('/elearning/{id}/questions', 'ElearningQuestionController');
            Route::get('/elearning/download/{name}', 'ElearningController@download_pdf')->name('download_pdf');
            Route::get('/elearning/file/{name}', 'ElearningController@viewFile')->name('elearning.file.view');
            Route::get('/elearning/{id}/file', 'ElearningController@deleteFile')->name('elearning.file.delete');
            Route::get('/training/download/{name}', 'TrainingController@viewFile')->name('training.download');
            Route::get('/training/{id}/file', 'TrainingController@deleteFile')->name('training.file.delete');
        });
    });


    // Routes for Doctor role
    Route::group(['middleware' => 'role:doctor', 'prefix' => 'account', 'namespace' => 'Doctor'], function () {
        Route::name('doctor.')->group(function () {

            Route::get('/', 'HomeController@index')->name('home');
            Route::resource('/devices', 'PracticeDevicesController');
            Route::get('/report/{id}', 'PracticeDevicesController@report');
            Route::get('/createtest/{id}', 'PracticeDevicesController@createtest');
            Route::post('/createtest/store', 'PracticeDevicesController@storetest');
            Route::post('/devices/filter', 'PracticeDevicesController@filterDevices');
            Route::post('/get-devices-by-practice', 'PracticeDevicesController@getDevicesByPractice')->name('getDevicesByPractice');
            Route::post('/employee/add', 'UsersController@storeEmployee');
            Route::resource('/employees', 'UsersController');
            Route::get('/profile/edit', 'UsersController@profileEdit')->name('profile.edit');
            Route::resource('/training', 'DoctorTrainingController');
            Route::get('/training/download/{name}', 'DoctorTrainingController@downloadFile');
            Route::post('/profile/update', 'UsersController@profileUpdate')->name('profile.update');
            Route::post('/profile/password', 'UsersController@profileUpdatePassword')->name('profile.update.password');
            Route::resource('/elearning', 'DoctorElearningController');
            Route::resource('/elearning/{id}/questions', 'DoctorElearningQuestionController');
            Route::get('/elearning/download/{name}', 'DoctorElearningController@download_pdf')->name('download_pdf');
            Route::get('/elearning/file/{name}', 'ElearningController@viewFile')->name('elearning.file.view');
            Route::get('/elearning/{id}/file', 'ElearningController@deleteFile')->name('elearning.file.delete');
            Route::get('/training/file/{name}', 'DoctorTrainingController@viewFile')->name('training.file.view');
            Route::get('/training/{id}/file', 'DoctorTrainingController@deleteFile')->name('training.file.delete');

        });
    });


    Route::group(['middleware' => 'role:employee', 'prefix' => 'user', 'namespace' => 'User'], function () {
        Route::name('user.')->group(function () {

            Route::get('/', 'HomeController@index')->name('home');
            Route::get('/training', 'UserTrainingController@index');
            Route::get('/training/{name}', 'UserTrainingController@downloadFile');
            Route::resource('/devices', 'PracticeDevicesController');

app/Models/Device.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Device extends Model
{
    use SoftDeletes;
    protected $with = ['user'];

    public function manufacturer(){
        return $this->belongsTo(Manufacturer::class);
    }



    public function type(){
        return $this->belongsTo(Type::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }


    public function practices()
    {
        return $this->belongsToMany(Practice::class)->withPivot('id','deleted_at','next_validation_date');
    }

    public static function getDeviceById($id)
    {
        return Device::find($id);
    }

    public static function getDevice()
    {
        return Device::with('manufacturer', 'type','user')->get();
    }

    public static function approveCustomDevice($id,$valDate){
        $device = Device::find($id);
        $device->status = 1;
        $device->user_id = 1;
        $device->val_duration = $valDate;

        $device->save();
        session()->forget('approve_id');
    }
    public static function privateCustomDevice($id,$valDate){
        $device = Device::find($id);
        $device->status = 1;
        $device->val_duration = $valDate;

        $device->save();
        session()->forget('approve_id');
    }
    public static function approve($id)
    {


        $device = Device::find($id);

        if($device->val_duration){
            $device->status = 1;
            $device->user_id = 1;
            $device->save();
            return 'ok';
        }else{
            // device validation period is not set
            return $device;
        }

    }
    public static function keepPrivate($id)
    {
        $device = Device::find($id);
        if($device->val_duration){
            $device->status = 1;
            $device->save();
            return 'ok';
        }else{
            // device validation period is not set
            return $device;
        }
    }

    public static function storeDevice($params)
    {
        return self::createOrUpdate(null, $params);
    }

    public static function updateDevice($device, $params)
    {
        return self::createOrUpdate($device, $params);
    }

    public static function deleteDevice($device)
    {
        $device->delete();
    }

    private static function createOrUpdate($device, $params)
    {
        if (!isset($device) || (isset($device) && !$device)) {
            $device = new Device;
            $device->user_id = auth()->id();
        }

        $device->manufacturer_id = $params['manufacturer_id'] ;
        $device->type_id = $params['type_id'] ;
        $device->val_duration = $params['val_duration'] ;
        $device->name = $params['name'] ;

        return $device->save();
    }
}

resources/views/admin/devices/create.blade.php
@extends('layouts.admin')
@section('meta_title', $meta_title)
@section('description')
    <div class="description">{{$translations['device_create_desc'] ?? 'action'}}</div>
@endsection
@section('content')
    <div class="container">
        <div class="kt-grid">
            <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v4__wrapper">

                <!--begin: Form Wizard Form-->
                <form class="kt-form" id="kt_user_add_form" method="POST"
                      action="{{ url('/') }}/{{app()->getLocale()}}/devices">
                @csrf
                <!--begin: Form Wizard Step 1-->
                    <div class="kt-wizard-v4__content" data-ktwizard-type="step-content"
                         data-ktwizard-state="current">
                        <div class="kt-section kt-section--first">
                            <div class="kt-wizard-v4__form">
                                <div class="row">
                                    <div class="col-xl-12">
                                        <div class="kt-section__body">
                                            <div class="form-group row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['manufacturer'] ?? 'manufacturer'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <select class="form-control" name="manufacturer_id">
                                                        @foreach($manufactorers as $manufactorer)
                                                            <option value="{{$manufactorer->id}}">{{$manufactorer->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['type'] ?? 'type'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <select class="form-control" name="type_id">
                                                        @foreach($types as $type)
                                                            <option value="{{$type->id}}">{{$type->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['validation_duration'] ?? 'validation_duration'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <select class="form-control" name="val_duration">
                                                            <option value="1">1 {{ $translations['year'] ?? 'year'}}</option>
                                                            <option value="2">2 {{ $translations['years'] ?? 'years'}}</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group form-group-last row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['name'] ?? 'name'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end: Form Wizard Step 1-->

                    <!--begin: Form Actions -->
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">
                            {{ $translations['create'] ?? 'create'}}
                        </button>
                    </div>

                    <!--end: Form Actions -->
                </form>

                <!--end: Form Wizard Form-->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/devices/edit.blade.php
@extends('layouts.admin')
@section('meta_title', $meta_title)
@section('description')
    <div class="description">{{$translations['device_edit_desc'] ?? 'device_edit_desc'}}</div>
@endsection
@section('content')
    <div class="container">
        <div class="kt-grid">
            <div class="kt-grid__item kt-grid__item--fluid kt-wizard-v4__wrapper">

                <!--begin: Form Wizard Form-->
                <form class="kt-form" id="kt_user_add_form" method="POST"
                      action="{{ url('/') }}/{{app()->getLocale()}}/devices/{{$device->id}}">
                @csrf
                {{method_field('PUT')}}
                <!--begin: Form Wizard Step 1-->
                    <div class="kt-wizard-v4__content" data-ktwizard-type="step-content"
                         data-ktwizard-state="current">
                        <div class="kt-section kt-section--first">
                            <div class="kt-wizard-v4__form">
                                <div class="row">
                                    <div class="col-xl-12">
                                        <div class="kt-section__body">
                                            <div class="form-group row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['manufacturer'] ?? 'manufacturer' }}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <select class="form-control" name="manufacturer_id">
                                                        @foreach($manufactorers as $manufactorer)
                                                            <option {{ (int)$device->manufactorer_id === (int)$manufactorer->id ? 'selected' : '' }} value="{{$manufactorer->id}}">{{$manufactorer->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['type'] ?? 'type'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <select class="form-control" name="type_id">
                                                        @foreach($types as $type)
                                                            <option {{ (int)$device->type_id === (int)$type->id ? 'selected' : '' }} value="{{$type->id}}">{{$type->name}}</option>
                                                        @endforeach
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['validation_duration'] ?? 'validation_duration'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <select class="form-control" name="val_duration">
                                                        <option value="1" {{(int)$device->val_duration === 1 ? 'selected' : ''}} >1 {{ $translations['year'] ?? 'year'}}</option>
                                                        <option value="2" {{(int)$device->val_duration === 2 ? 'selected' : ''}}>2 {{ $translations['years'] ?? 'years'}}</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group form-group-last row">
                                                <label class="col-xl-3 col-lg-3 col-form-label">{{ $translations['name'] ?? 'name'}}</label>
                                                <div class="col-lg-9 col-xl-9">
                                                    <div class="input-group">
                                                        <input type="text" class="form-control" value="{{$device->name}}" name="name" required>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--end: Form Wizard Step 1-->

                    <!--begin: Form Actions -->
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-success btn-md btn-tall btn-wide kt-font-bold kt-font-transform-u">
                            {{ $translations['update'] ?? 'Update' }}
                        </button>
                    </div>

                    <!--end: Form Actions -->
                </form>

                <!--end: Form Wizard Form-->
            </div>
        </div>
    </div>

@endsection

resources/views/admin/devices/home.blade.php
@extends('layouts.admin')
@section('meta_title', $meta_title)
@section('actionbutton')
    <div class="kt-subheader__wrapper">

        <a class="btn btn-primary" href="{{ url('/') }}/{{app()->getLocale()}}/download/devices">
            {{ $translations['export_list'] ?? 'export_list' }}
        </a>

        <a class="btn btn-danger" href="{{ url('/') }}/{{app()->getLocale()}}/devices/create">
            {{ $translations['add_new_device'] ?? 'add_new_device' }}
        </a>

    </div>
@endsection
@section('description')
    <div class="description">{{$translations['device_home_desc'] ?? 'action'}}</div>
@endsection
@section('content')

<div class="table-responsive">
    <table id="devicesList" class="table">
        <thead class="thead-light">
        <tr>
            <th>{{ $translations['name'] ?? 'name' }}</th>
            <th>{{ $translations['manufacturer'] ?? 'manufacturer' }}</th>
            <th>{{ $translations['type'] ?? 'type' }}</th>
            <th>{{ $translations['validation_duration'] ?? 'validation_duration' }}</th>
            <th>{{ $translations['status'] ?? 'status' }}</th>
            <th>{{ $translations['action'] ?? 'Action'}}</th>
        </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
@endsection
@push('modal')
    @include('partials.delete', ['modal_title' => $translations['are_you_sure'] ?? 'are_you_sure'])
@endpush
@push('scripts')
    <script>
        $(document).ready(function () {
            $('#devicesList').DataTable({
                "bProcessing": true,
                "bServerSide": true,
                "ajax": "{{route('devices.index',['locale'=>app()->getLocale()])}}",
                "language": {
                    "emptyTable": "{{ $translations['no_devices'] ?? 'no_devices'}}"
                },
                "columns": [
                    {"data": "name"},
                    {
                        "name":"manufacturer.name",
                        "data": "manufacturer",
                        "render": function (manufacturer) {
                            return manufacturer ? manufacturer.name : '-';
                        }
                    },
                    {
                        "name":"type.name",
                        "data": "type",
                        "render": function (type) {
                            return type ? type.name : '-';
                        }
                    },
                    {
                        "data": "val_duration",
                        "searchable": false,
                        "render": function (duration) {
                            return duration + " " + "{{ $translations['year'] ?? 'year' }}";
                        }
                    },
                    {
                        "name":"user.name",
                        "data": "status",
                        "searchable": false,
                        "render": function (status, type, device) {
                            return status === 1 ? "{{($translations['public'] ?? 'public')}}" : device.user.name;
                        }
                    },
                    {
                        "data": "status",
                        "className": "my_action",
                        "searchable": false,
                        "orderable": false,
                        "render": function (status, type, device) {
                            let html;
                            let url = "{{url('/').'/'.app()->getLocale()}}/devices/" + device.id;
                            let edit = document.createElement("a");
                            let del = document.createElement("button");
                            edit.className = 'btn btn-success my_btn1';
                            edit.setAttribute('role', 'button');
                            edit.href = url + "/edit";
                            edit.innerText = "{{ $translations['edit'] ?? 'Edit' }}";
                            del.className = 'btn btn-danger delete_action';
                            del.type = 'button';
                            del.setAttribute('data-form_action', url);
                            del.setAttribute('data-toggle', 'modal');
                            del.setAttribute('data-target', '#deleteModal');
                            del.innerText = "{{ $translations['delete'] ?? 'Delete' }}";
                            html = edit.outerHTML + " " + del.outerHTML;
                            if (parseInt(device.status) !== 1 && parseInt(device.user_id) !== 0) {
                                let text = "{{ $translations['are_you_sure'] ?? 'are_you_sure'}}";
                                let a1 = document.createElement("a");
                                let a2 = document.createElement("a");
                                a1.setAttribute('role', 'button');
                                a2.setAttribute('role', 'button');
                                a1.href = "{{url('/')}}/approveDevice/" + device.id;
                                a2.href = "{{url('/')}}/keepPrivet/" + device.id;
                                a1.className = 'btn btn-primary';
                                a2.className = 'btn btn-warning';
                                a1.innerText = "{{ $translations['approve'] ?? 'approve'}}";
                                a2.innerText = "{{ $translations['keep_private'] ?? 'keep_private'}}";
                                a1.setAttribute("onclick", "return confirm('" + text + "')");
                                a2.setAttribute("onclick", "return confirm('" + text + "')");
                                html += " " + a1.outerHTML + " " + a2.outerHTML;
                            }
                            return html;
                        }
                    }
                ],
            });
        })
    </script>
    @endpush