routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Exports\DeviceTypesExport;
use App\Exports\DoctorsExport;
use App\Exports\EmployeesExport;
use App\Exports\PracticesExport;
use App\Exports\RegionalAdminsExport;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\QualificationsExport;
use App\Exports\ServicesExport;
use App\Exports\DevicesExport;
use App\Exports\PracticeDevicesExport;
use App\Exports\ManufacturersExport;

Route::get('/', 'HomeController@index')->name('home');

Route::group([
    'prefix' => '{locale}',
    'where' => ['locale' => '[a-zA-Z]{2}'],
    'middleware' => 'setlocale',
], function () {
    Auth::routes();
});

Route::group([
    'prefix' => '{locale}',
    'where' => ['locale' => '[a-zA-Z]{2}'],
    'middleware' => 'setlocale',
], function () {

    Route::namespace('Admin')->group(function () {
        Route::group(['middleware' => 'role:superadmin'], function () {
            Route::get('/', 'HomeController@index')->name('admin.home');
            Route::resource('/users', 'UsersController');
            Route::post('/elearning/filter', 'ElearningController@filterDevices')->name('admin.filter');
            Route::get('/doctors', 'UsersController@doctors')->name('doctors.home');
            Route::get('/doctors/createdoctor', 'UsersController@addDoctor');
            Route::get('/doctors/{id}/editDoctor', 'UsersController@editDoctor');
            Route::post('/doctors/storedoctor', 'UsersController@storeDoctor');
            Route::get('/reports/generate', 'ReportController@generate')->name('report.generate');
            Route::post('/reports/generate', 'ReportController@dataCreate');

            Route::post('/reports/store', 'ReportController@store')->name('report.store');

            //Route::post('/reports/store', 'ReportController@dataStore')->name('report.store');
            Route::get('/reports', 'ReportController@index');
            Route::get('/show/reports', 'ReportController@show')->name('report.show');
            Route::post('/report/{id}/pdf-download', 'ReportController@downloadPDF')->name('report.download');
            Route::delete('/report/{id}/delete', 'ReportController@delete')->name('report.delete');
            Route::get('/report/{id}/edit', 'ReportController@dataCreate')->name('report.edit');


            Route::resource('/sites', 'SiteController');
            Route::post('/elearning/getsites', 'SiteController@getSitesByPractice')->name('admin.getSitesByPractice');


            Route::group(['prefix' => 'download'], function () {
                Route::get('/devices', function () {
                    return Excel::download(new DevicesExport, 'Devices.xlsx');
                })->middleware('auth');
                Route::get('/practicedevices', function () {
                    return Excel::download(new PracticeDevicesExport, 'PracticeDevices.xlsx');
                })->middleware('auth');
                Route::get('/services', function () {
                    return Excel::download(new ServicesExport, 'Services.xlsx');
                })->middleware('auth');
                Route::get('/qualifications', function () {
                    return Excel::download(new QualificationsExport, 'Qualifications.xlsx');
                })->middleware('auth');
                Route::get('/manufacturers', function () {
                    return Excel::download(new ManufacturersExport, 'Manufacturer.xlsx');
                })->middleware('auth');
                Route::get('/types', function () {
                    return Excel::download(new DeviceTypesExport, 'DeviceTypes.xlsx');
                })->middleware('auth');
                Route::get('/practice', function () {
                    return Excel::download(new PracticesExport, 'Practice.xlsx');
                })->middleware('auth');
                Route::get('/employee', function () {
                    return Excel::download(new EmployeesExport, 'Employees.xlsx');
                })->middleware('auth');
                Route::get('/doctor', function () {
                    return Excel::download(new DoctorsExport, 'Doctors.xlsx');
                })->middleware('auth');
                Route::get('/admin', function () {
                    return Excel::download(new RegionalAdminsExport, 'RegionalAdmins.xlsx');
                })->middleware('auth');
            });


            Route::get('/changelogin/', 'UsersController@changelogin');
            Route::put('/changelogin/store', 'UsersController@updatepassword');


            Route::get('/doctors/createpassword/{token}', 'SendMailController@createpassword');
            Route::put('/doctors/createpassword/{token}/store', 'SendMailController@updatepassword');
            Route::get('/doctor/{id}/edit', 'UsersController@editDoctor');
            Route::get('/employees', 'UsersController@employees')->name('employees.index');
            Route::get('/admins', 'UsersController@admins')->name('admins.index');
            Route::get('/createemployee', 'UsersController@addEmployee');
            Route::get('/createadmin', 'UsersController@addAdmin');
            Route::post('/employees/storeemployee', 'UsersController@storeEmployee');
            Route::post('/admins/storeadmin', 'UsersController@storeAdmin');
            Route::put('/employees/{id}', 'UsersController@updateEmployee');
            Route::put('/admin/{id}', 'UsersController@updateAdmin');
            Route::get('/employee/{id}/edit', 'UsersController@editEmployee');
            Route::get('/admin/{id}/edit', 'UsersController@editAdmin');
            Route::resource('/settings', 'SettingsController');
            Route::resource('/devices', 'DevicesController');
            Route::resource('/qualifications', 'QualificationsController');
            Route::resource('/types', 'TypesController');
            Route::resource('/practices', 'PracticesController');
            Route::resource('/translations', 'TranslationsController');
            Route::resource('/manufacturers', 'ManufacturersController');
            Route::resource('/services', 'ServicesController');
            Route::resource('/practice-devices', 'PracticeDevicesController');
            Route::resource('/elearning', 'ElearningController');
            Route::resource('/training', 'TrainingController');
            Route::resource('/elearning/{id}/questions', 'ElearningQuestionController');
            Route::get('/elearning/download/{name}', 'ElearningController@download_pdf')->name('download_pdf');
            Route::get('/elearning/file/{name}', 'ElearningController@viewFile')->name('elearning.file.view');
            Route::get('/elearning/{id}/file', 'ElearningController@deleteFile')->name('elearning.file.delete');
            Route::get('/training/download/{name}', 'TrainingController@viewFile')->name('training.download');
            Route::get('/training/{id}/file', 'TrainingController@deleteFile')->name('training.file.delete');
        });
    });


    // Routes for Doctor role
    Route::group(['middleware' => 'role:doctor', 'prefix' => 'account', 'namespace' => 'Doctor'], function () {
        Route::name('doctor.')->group(function () {

            Route::get('/', 'HomeController@index')->name('home');
            Route::resource('/devices', 'PracticeDevicesController');
            Route::get('/report/{id}', 'PracticeDevicesController@report');
            Route::get('/createtest/{id}', 'PracticeDevicesController@createtest');
            Route::post('/createtest/store', 'PracticeDevicesController@storetest');
            Route::post('/devices/filter', 'PracticeDevicesController@filterDevices');
            Route::post('/get-devices-by-practice', 'PracticeDevicesController@getDevicesByPractice')->name('getDevicesByPractice');
            Route::post('/employee/add', 'UsersController@storeEmployee');
            Route::resource('/employees', 'UsersController');
            Route::get('/profile/edit', 'UsersController@profileEdit')->name('profile.edit');
            Route::resource('/training', 'DoctorTrainingController');
            Route::get('/training/download/{name}', 'DoctorTrainingController@downloadFile');
            Route::post('/profile/update', 'UsersController@profileUpdate')->name('profile.update');
            Route::post('/profile/password', 'UsersController@profileUpdatePassword')->name('profile.update.password');
            Route::resource('/elearning', 'DoctorElearningController');
            Route::resource('/elearning/{id}/questions', 'DoctorElearningQuestionController');
            Route::get('/elearning/download/{name}', 'DoctorElearningController@download_pdf')->name('download_pdf');
            Route::get('/elearning/file/{name}', 'ElearningController@viewFile')->name('elearning.file.view');
            Route::get('/elearning/{id}/file', 'ElearningController@deleteFile')->name('elearning.file.delete');
            Route::get('/training/file/{name}', 'DoctorTrainingController@viewFile')->name('training.file.view');
            Route::get('/training/{id}/file', 'DoctorTrainingController@deleteFile')->name('training.file.delete');

        });
    });


    Route::group(['middleware' => 'role:employee', 'prefix' => 'user', 'namespace' => 'User'], function () {
        Route::name('user.')->group(function () {

            Route::get('/', 'HomeController@index')->name('home');
            Route::get('/training', 'UserTrainingController@index');
            Route::get('/training/{name}', 'UserTrainingController@downloadFile');
            Route::resource('/devices', 'PracticeDevicesController');

app/Http/Controllers/Doctor/DoctorElearningQuestionAnswerController.php
<?php

namespace App\Http\Controllers\Doctor;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DoctorElearningQuestionAnswerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Doctor/DoctorElearningQuestionController.php
<?php

namespace App\Http\Controllers\Doctor;

use App\Models\Elearning;
use App\Models\ElearningQuestion;
use App\Models\ElearningQuestionsAnswer;
use App\Models\Translation;
use Exception;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Routing\Redirector;
use Illuminate\Support\Collection;
use Illuminate\View\View;

class DoctorElearningQuestionController extends Controller
{


    /**
     * @param Request $request
     * @param string $lang
     * @param int $id
     * @return Factory|View
     * @throws Exception
     */
    public function index(Request $request, string $lang, int $id)
    {
        $elearning = Elearning::query()->findOrFail($id, ['id']);
        if ($request->ajax()) return datatables()->of(Elearning::query()->with(['questions' => function ($query) {
            $query->with('answers');
        }])->find($elearning->id)->questions)->make(true);
        $translations = Translation::all()->pluck(app()->getLocale(), 'short_code');
        $data = [
            'elearning' => $elearning,
            'parent_link' => route('doctor.elearning.index', ['locale' => app()->getLocale()]),
            'meta_title' => $translations['elearning'] ?? 'Elearning',
        ];
        return view('doctor.elearning_question.home', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }


    /**
     * @param Request $request
     * @param string $lang
     * @param int $id
     * @return RedirectResponse
     */
    public function store(Request $request, string $lang, int $id)
    {
        $translations = Translation::all()->pluck($lang, 'short_code');
        $question = ElearningQuestion::query()->create([
            'question' => $request->question,
            'elearning_id' => $id
        ]);
        foreach ($request->answer as $key => $value){
            ElearningQuestionsAnswer::query()->create([
                'answer' => $value,
                'type' => $request->type[$key],
                'elearning_question_id' => $question->id
            ]);

        }
        $request->session()->flash('type', 'success');
        $request->session()->flash('message', $translations['quest_with_answer'] ?? 'Question with answers were successfully created');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param string $lang
     * @param int $elearning_id
     * @param int $question_id
     * @return Factory|View
     */
    public function edit(string $lang, int $elearning_id, int $question_id)
    {
        $translations = Translation::all()->pluck(app()->getLocale(), 'short_code');
        $data = [
            'meta_title' => $translations['question'] ?? 'Devices',
            'meta_parent' => $translations['edit_quest'] ?? 'Edit Question',
            'question' => ElearningQuestion::getQuestionByID($question_id),
            'parent_link' => url("/")."/{$lang}/account/elearning/{$elearning_id}/questions",
        ];
        return view('doctor.elearning_question.edit',$data);
    }

    /**
     * @param Request $request
     * @param string $lang
     * @param int $elearning_id
     * @param int $question_id
     * @return RedirectResponse|Redirector
     */
    public function update(Request $request, string $lang, int $elearning_id, int $question_id)
    {
        $translations = $this->updateFuncFromAdmin($request, $question_id);
        $request->session()->flash('message', $translations['quest_with_answer_update'] ?? $translations['quest_with_answer_update'] ?? 'Question with answers were successfully updateed');
        $url = url("/") . "/{$lang}/account/elearning/{$elearning_id}/questions";
        return redirect($url);
    }


    /**
     * @param string $lang
     * @param int $id
     * @param int $questionID
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(string $lang, int $id, int $questionID)
    {
        try {
            ElearningQuestion::with(['answers' => function ($query) {
                $query->delete();
            }])->findOrFail($questionID)->delete();
        } catch (Exception $e) {
            request()->session()->flash('type', 'danger');
            request()->session()->flash('message', $e->getMessage());
            return redirect()->back();
        }
        request()->session()->flash('type', 'success');
        request()->session()->flash('message', $translations['success'] ?? 'Action completed successfully');
        return redirect()->back();
    }


    /**
     * @param object $request
     * @param int $question_id
     * @return Collection
     */
    public function updateFuncFromAdmin($request, int $question_id)
    {
        $translations = Translation::all()->pluck(app()->getLocale(), 'short_code');
        try {
            ElearningQuestion::query()->findOrFail($question_id)->update([
                'question' => $request->question,
            ]);
            ElearningQuestionsAnswer::query()->where('elearning_question_id', $question_id)->delete();

            foreach ($request->answer as $key => $value){
                ElearningQuestionsAnswer::query()->create([
                    'answer' => $value,
                    'type' => $request->type[$key],
                    'elearning_question_id' => $question_id
                ]);
            }
        } catch (Exception $e) {
            $request->session()->flash('type', 'danger');
            return $translations;
        }
        //dd(count($request->answer));
        $request->session()->flash('type', 'success');
        return $translations;
    }
}

resources/views/doctor/profile/edit.blade.php
@extends('layouts.doctor')
@section('meta_title', $meta_title)
@section('description')
    <div class="description">{{$translations['doc_profile_edit_desc'] ?? 'action'}}</div>
@endsection
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="POST"
                          action="{{ route('doctor.profile.update',['locale'=>app()->getLocale(),'id'=>$user->id] ) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="name"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['first_name'] ?? 'First Name'}}</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                       name="name" value="{{$user->name}}" required autocomplete="name" autofocus>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['last_name'] ?? 'last_name'}}</label>
                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror"
                                       name="last_name" value="{{$user->last_name}}" required>
                                @error('last_name')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['email'] ?? 'email'}}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                       name="email" value="{{$user->email}}" required>

                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['title'] ?? 'title'}}</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control @error('email') is-invalid @enderror"
                                       name="title" value="{{$user->title}}" required>

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['phone'] ?? 'phone'}}</label>

                            <div class="col-md-6">
                                <input id="email" type="text"
                                       class="form-control @error('email') is-invalid @enderror"
                                       name="phone" value="{{$user->phone}}" required>

                                @error('phone')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ $translations['update'] ?? 'Update' }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8 mt-4">
            <div class="card">
                <div class="card-body">
                    <form method="POST"
                          action="{{ route('doctor.profile.update.password',['locale'=>app()->getLocale()] ) }}">
                        @csrf
                        <div class="form-group row">
                            <label for="old_password"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['old_password'] ?? 'old_password'}}</label>

                            <div class="col-md-6">
                                <input id="old_password" type="password"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="old_password" value="" required autocomplete="password" autofocus>

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['new_password'] ?? 'new_password'}}</label>

                            <div class="col-md-6">
                                <input id="pwd" type="password"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="password" value="" required autofocus>
                                <div id="pwd_strength_wrap" class="pwd3">
                                    <div id="passwordDescription">{{ $translations['pass_not_ent'] ?? 'Password not entered' }}</div>
                                    <div id="passwordStrength" class="strength0"></div>
                                    <div id="pswd_info">
                                        <strong>{{ $translations['strong_pass'] ?? 'Strong Password Tips' }}:</strong>
                                        <ul>
                                            <li class="invalid" id="length">{{ $translations['min_six'] ?? 'At least 6 characters' }}</li>
                                            <li class="invalid" id="pnum">{{ $translations['one_num'] ?? 'At least one number' }}</li>
                                            <li class="invalid" id="capital">{{ $translations['one_low_one_up'] ?? 'At least one lowercase & one uppercase letter' }}</li>
                                            <li class="invalid" id="spchar">{{ $translations['min_one_char'] ?? 'At least one special character' }}</li>
                                        </ul>
                                    </div><!-- END pswd_info -->
                                </div>
                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="password_confirmation"
                                   class="col-md-4 col-form-label text-md-right">{{$translations['confirm_new_password'] ?? 'confirm_new_password'}}</label>

                            <div class="col-md-6">
                                <input id="password_confirmation" type="password"
                                       class="form-control @error('name') is-invalid @enderror"
                                       name="password_confirmation" value="" required autofocus>

                                @error('password')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ $translations['update'] ?? 'Update' }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection